.PHONY: final

all: final
final:
	pdflatex final-report.tex
	pdflatex final-report.tex
	evince final-report.pdf &
compile:
	pdflatex final-report.tex
	pdflatex final-report.tex
curate:
	rm *.aux
	rm *.log
clean:
	rm *.pdf 
	rm *.aux 
	rm *.log 